
export const africaCountries: {
  name: string;
  iso2: string;
  dialCode: string;
}[] = [
  { name: 'Algeria', iso2: 'DZ', dialCode: '213' },
  { name: 'Angola', iso2: 'AO', dialCode: '244' },
  { name: 'Benin', iso2: 'BJ', dialCode: '229' },
  { name: 'Botswana', iso2: 'BW', dialCode: '267' },
  { name: 'Burkina Faso', iso2: 'BF', dialCode: '226' },
  { name: 'Burundi', iso2: 'BI', dialCode: '257' },
  { name: 'Cabo Verde', iso2: 'CV', dialCode: '238' },
  { name: 'Cameroon', iso2: 'CM', dialCode: '237' },
  { name: 'Central African Republic', iso2: 'CF', dialCode: '236' },
  { name: 'Chad', iso2: 'TD', dialCode: '235' },
  { name: 'Comoros', iso2: 'KM', dialCode: '269' },
  { name: 'Congo (Republic)', iso2: 'CG', dialCode: '242' },
  { name: 'Congo (DRC)', iso2: 'CD', dialCode: '243' },
  { name: 'Djibouti', iso2: 'DJ', dialCode: '253' },
  { name: 'Egypt', iso2: 'EG', dialCode: '20' },
  { name: 'Equatorial Guinea', iso2: 'GQ', dialCode: '240' },
  { name: 'Eritrea', iso2: 'ER', dialCode: '291' },
  { name: 'Eswatini', iso2: 'SZ', dialCode: '268' },
  { name: 'Ethiopia', iso2: 'ET', dialCode: '251' },
  { name: 'Gabon', iso2: 'GA', dialCode: '241' },
  { name: 'Gambia', iso2: 'GM', dialCode: '220' },
  { name: 'Ghana', iso2: 'GH', dialCode: '233' },
  { name: 'Guinea', iso2: 'GN', dialCode: '224' },
  { name: 'Guinea-Bissau', iso2: 'GW', dialCode: '245' },
  { name: 'Ivory Coast', iso2: 'CI', dialCode: '225' },
  { name: 'Kenya', iso2: 'KE', dialCode: '254' },
  { name: 'Lesotho', iso2: 'LS', dialCode: '266' },
  { name: 'Liberia', iso2: 'LR', dialCode: '231' },
  { name: 'Libya', iso2: 'LY', dialCode: '218' },
  { name: 'Madagascar', iso2: 'MG', dialCode: '261' },
  { name: 'Malawi', iso2: 'MW', dialCode: '265' },
  { name: 'Mali', iso2: 'ML', dialCode: '223' },
  { name: 'Mauritania', iso2: 'MR', dialCode: '222' },
  { name: 'Mauritius', iso2: 'MU', dialCode: '230' },
  { name: 'Morocco', iso2: 'MA', dialCode: '212' },
  { name: 'Mozambique', iso2: 'MZ', dialCode: '258' },
  { name: 'Namibia', iso2: 'NA', dialCode: '264' },
  { name: 'Niger', iso2: 'NE', dialCode: '227' },
  { name: 'Nigeria', iso2: 'NG', dialCode: '234' },
  { name: 'Rwanda', iso2: 'RW', dialCode: '250' },
  { name: 'São Tomé and Príncipe', iso2: 'ST', dialCode: '239' },
  { name: 'Senegal', iso2: 'SN', dialCode: '221' },
  { name: 'Seychelles', iso2: 'SC', dialCode: '248' },
  { name: 'Sierra Leone', iso2: 'SL', dialCode: '232' },
  { name: 'Somalia', iso2: 'SO', dialCode: '252' },
  { name: 'South Africa', iso2: 'ZA', dialCode: '27' },
  { name: 'South Sudan', iso2: 'SS', dialCode: '211' },
  { name: 'Sudan', iso2: 'SD', dialCode: '249' },
  { name: 'Tanzania', iso2: 'TZ', dialCode: '255' },
  { name: 'Togo', iso2: 'TG', dialCode: '228' },
  { name: 'Tunisia', iso2: 'TN', dialCode: '216' },
  { name: 'Uganda', iso2: 'UG', dialCode: '256' },
  { name: 'Zambia', iso2: 'ZM', dialCode: '260' },
  { name: 'Zimbabwe', iso2: 'ZW', dialCode: '263' }
];