export const users = [
  {
    id: 1,
    name: "James Anderson",
    email: "olivia@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 12,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 2,
    name: "Michael Johnson",
    email: "phoenix@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 21,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 3,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 4,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 5,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 6,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 7,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 8,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 9,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 10,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 11,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 12,
    name: "David Brown",
    email: "lana@jsmastery.pro",
    joined: "Jan 6, 2022",
    itinerary: 15,
    status: "User",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
  },
];
